[package]
name = "SharkDB"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_derive = "1.0"  # 允许使用 #[derive(Serialize, Deserialize)] 注解
serde_bytes = "0.11.15"
fs4 = "0.8.4"
tempfile = "3.12.0"

